global:
  scrape_interval: 10s
  scrape_timeout: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['host.docker.internal:3000']
  - job_name: 'prometheus'
    scrape_interval: 5s
    metrics_path: '/api/metrics'

    static_configs:
      - targets: ['host.docker.internal:3000']
        labels:
          service: 'backend-demo-app'
          group: 'backend'

rule_files:
  - 'alert.rules'