name: backend
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yarn Install
        run: yarn --cwd backend-realtime
      - name: Run test
        run: yarn --cwd backend-realtime test
  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yarn Install
        run: yarn --cwd backend-realtime
      - name: TypeScript Build
        run: yarn --cwd backend-realtime build
