name: frontend
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yarn Install
        run: yarn --cwd frontend
      - name: Run Lint
        run: yarn --cwd frontend lint
